# Site settings
title: Neeloy's homepage
email:
description: "" # On the 'about' section
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neeloy-banerjee.github.io" 
twitter_username: NeeloyBanerjee
github_username:  neeloy-banerjee

# Build settings
markdown: kramdown
theme: minima

